[tool.poetry]
name = "cogmyra"
version = "0.3.5"
description = "CogMyra local API (FastAPI + OpenAI) with simple logging"
authors = ["CogMyra <dev@cogmyra.com>"]
# If you later add a real Python package, list it here.
packages = []

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
fastapi = "0.111.1"
uvicorn = "0.30.6"
python-dotenv = "^1.0.1"
sqlalchemy = "^2.0.34"
pydantic = "^2.8.2"
openai = "^1.40.0"
python-multipart = "^0.0.20"
jinja2 = "^3.1.6"

# Dev-only tools (NOT installed on Render when we use --without dev)
[tool.poetry.group.dev.dependencies]
fastapi-cli = "^0.0.12"
ruff = "^0.5.7"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
