[tool.poetry]
name = "cogmyra"
version = "0.3.5"
description = "CogMyra API (FastAPI)"
authors = ["CogMyra"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = "^0.111.0"
uvicorn = "^0.30.0"
python-dotenv = "^1.0.1"
openai = "^1.37.0"
sqlalchemy = "^2.0.30"
pydantic = "^2.8.0"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.0"
pre-commit = "^3.7.0"
watchfiles = "^0.21.0"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
